
CREATE TABLE PRODUCTO(
idProducto INT PRIMARY KEY,
nombre NVARCHAR2(25),
precio NUMBER(9,2),
stock INT);


-- ALTER TABLE PRODUCTO (alterar tabla)
-- ADD COLUMN (añadir una nueva columna)
-- DROP TABLE PRODUCTO; (borrar la tabla por completo)
-- DROP TABLE PRODUCTO;

INSERT INTO PRODUCTO(IDPRODUCTO, NOMBRE, PRECIO, STOCK)
VALUES(1, 'TECLADO', 9.99, 10);

INSERT INTO PRODUCTO(IDPRODUCTO, NOMBRE, PRECIO, STOCK)
VALUES(2, 'RATON', 19.99, 25);

UPDATE PRODUCTO
SET PRECIO = 11
WHERE IDPRODUCTO = 1;

/*DELETE FROM PRODUCTO
WHERE IDPRODUCTO = 1;*/

--SELECT * FROM PRODUCTO;

DESC PRODUCTO;

SELECT IDPRODUCTO, NOMBRE, PRECIO, STOCK 
FROM PRODUCTO
WHERE IDPRODUCTO = 2;

UPDATE PRODUCTO
SET IDPRODUCTO = 22, NOMBRE = 'RATON EDITADO', PRECIO = 20, STOCK = 20
WHERE IDPRODUCTO = 2;

SELECT IDPRODUCTO, NOMBRE, PRECIO, STOCK 
FROM PRODUCTO
WHERE IDPRODUCTO = 22;

SELECT * FROM PRODUCTO;

COMMIT;

--DROP TABLE PRODUCTO;

--SELECT * FROM PRODUCTO;